//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.Pedido = new HashSet<Pedido>();
        }
        
        
        public int ID { get; set; }
        [Display(Name = "Nombre y Apellido")]
        public string NombreApellido { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        [Display(Name = "CUIT o CUIL")]
        public string CuitCuil { get; set; }
        public string Domicilio { get; set; }
        public string Localidad { get; set; }
        [Display(Name = "Código Postal")]
        public string CodigoPostal { get; set; }
        public Nullable<bool> Activo { get; set; }
        [Display(Name = "Usuario final")]
        public Nullable<bool> EsUsuarioFinal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}
