//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Pedido
    {
        public long ID { get; set; }
        [Display(Name = "Cliente")]
        public int ClienteID { get; set; }
        [Display(Name = "Producto")]
        public short ProductoID { get; set; }
        [Display(Name = "Estado del pago")]
        public short EstadoPagoPedidoID { get; set; }
        [Display(Name = "Tipo de pedido")]
        public short TipoPedidoID { get; set; }
        [Display(Name = "Estado de fabricación")]
        public short EstadoFabricacionPedidoID { get; set; }
        [Display(Name = "Fecha de Entrega")]
        public Nullable<System.DateTime> FechaEstimadaEntrega { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        [Display(Name = "Fecha De Modificación")]
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public short Cantidad { get; set; }
        [Display(Name = "Subtotal")]
        public double TotalPrecio { get; set; }
        public string Observaciones { get; set; }
        public Nullable<bool> Activo { get; set; }
        [Display(Name = "Tipo de Carro")]
        public short TipoCarroID { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual EstadoFabricacionPedido EstadoFabricacionPedido { get; set; }
        public virtual EstadoPagoPedido EstadoPagoPedido { get; set; }
        public virtual Productos Productos { get; set; }
        public virtual TipoPedido TipoPedido { get; set; }
        public virtual TipoCarro TipoCarro { get; set; }
    }
}
