//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public long ID { get; set; }
        public int ClienteID { get; set; }
        public short ProductoID { get; set; }
        public short EstadoPagoPedidoID { get; set; }
        public short TipoPedidoID { get; set; }
        public short EstadoFabricacionPedidoID { get; set; }
        public Nullable<System.DateTime> FechaEstimadaEntrega { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public short Cantidad { get; set; }
        public double TotalPrecio { get; set; }
        public string Observaciones { get; set; }
        public Nullable<bool> Activo { get; set; }
        public short TipoCarroID { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual EstadoFabricacionPedido EstadoFabricacionPedido { get; set; }
        public virtual EstadoPagoPedido EstadoPagoPedido { get; set; }
        public virtual Productos Productos { get; set; }
        public virtual TipoPedido TipoPedido { get; set; }
        public virtual TipoCarro TipoCarro { get; set; }
    }
}
